import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Link } from '@tanstack/react-router';
import * as Dialog from '@radix-ui/react-dialog';
import { ArrowRight, ArrowUpRight, ChevronLeft, ChevronRight, MapPin, Phone, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ReserveButton } from './layout';
import { categories, dishes, gallery, images, restaurant, reviews, type Category } from '@/data/restaurant';

export function Reveal({ children, className = '' }: { children: ReactNode; className?: string }) {
 const ref = useRef<HTMLDivElement>(null);
 useEffect(() => { const el = ref.current; if (!el) return; const observer = new IntersectionObserver(entries => { if (entries.some(e => e.isIntersecting)) { el.classList.add('visible'); observer.disconnect(); } }, { threshold: .08 }); observer.observe(el); return () => observer.disconnect(); }, []);
 return <div ref={ref} className={`reveal ${className}`}>{children}</div>;
}
export function Eyebrow({ children }: { children: ReactNode }) { return <p className="eyebrow">{children}</p>; }
export function BranchArt() { return <svg className="branch-art" viewBox="0 0 110 150" fill="none" stroke="currentColor" strokeWidth="1" aria-hidden="true"><path d="M25 145C55 99 57 53 76 5M49 98C28 85 19 65 21 48C43 60 50 78 49 98ZM59 72C79 64 92 48 94 32C70 40 59 53 59 72ZM69 40C54 25 57 11 60 5C74 13 78 25 69 40ZM34 126C17 118 8 107 5 91C25 95 37 112 34 126ZM43 111C66 113 85 101 93 88C73 86 51 96 43 111" /></svg>; }
export function Hero() {
 return <section className="hero"><img className="hero-photo" src={images.hero} alt="A warm Middle Eastern table with grilled chicken, fragrant rice, hummus and fattoush salad" width="1920" height="1088" fetchPriority="high" /><div className="hero-inner"><Eyebrow>MIDDLE EASTERN · MULTI-CUISINE · CHENNAI</Eyebrow><h1><span>A Taste of the Middle East,</span><span>Served <em>With Soul.</em></span></h1><p className="hero-description">Flavourful kebabs, aromatic mandi, indulgent desserts and unforgettable moments — crafted for families, friends and celebrations.</p><div className="hero-actions"><ReserveButton /><Button asChild variant="diningOutline"><Link to="/menu">EXPLORE MENU<ArrowUpRight /></Link></Button></div></div><div className="hero-bottom"><a className="scroll-cue" href="#experience"><span className="scroll-line" />SCROLL TO DISCOVER</a><div className="hero-rating"><span className="stars" aria-label="Five stars">★★★★★</span><div><p><strong>4.7</strong> / 5</p><p>3,315+ guest reviews</p></div></div></div></section>;
}
export function PageIntro({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) {
 return <div className="page-intro"><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1>{description && <p>{description}</p>}</div>;
}
export function StorySection() {
 return <section id="experience" className="section story"><Reveal className="story-copy"><Eyebrow>THE FATTOUSH EXPERIENCE</Eyebrow><h2 className="section-title">Where Every Plate<br />Tells a Story</h2><p className="section-copy">Some meals are more than a meal. They’re a gathering, a conversation, a little celebration of life.</p><p className="section-copy mt-4">At Fattoush, Middle Eastern flavours meet a world of cuisines. From the warmth of our grills to the comfort of a shared platter, there’s something for everyone at our table.</p><Link to="/story" className="text-link">DISCOVER OUR STORY<ArrowUpRight /></Link></Reveal><Reveal className="story-visual"><div className="story-image reveal-image"><img src={images.feast} alt="Fattoush salad, creamy hummus and a platter of grilled kebabs, illustrative photograph" width="1536" height="1024" loading="lazy" /></div><span className="story-note">Made to be shared.</span></Reveal><BranchArt /></section>;
}
export function SignatureDishes() {
 const track = useRef<HTMLDivElement>(null);
 const featured = [dishes[1], dishes[14], dishes[4], dishes[15]].filter(d => d !== undefined);
 const scroll = (direction: number) => { const el = track.current; if (el) el.scrollBy({ left: direction * (el.clientWidth / 3 + 20), behavior: 'smooth' }); };
 return <section className="signature-band"><div className="section"><Reveal><div className="section-head"><div><Eyebrow>FROM OUR KITCHEN</Eyebrow><h2 className="section-title">Flavours Worth Coming Back For</h2><p className="section-subtitle">From smoky grills to fragrant rice and irresistible desserts.</p></div><div className="carousel-controls"><Button variant="diningIcon" aria-label="Previous dishes" onClick={() => scroll(-1)}><ChevronLeft /></Button><Button variant="diningIcon" aria-label="Next dishes" onClick={() => scroll(1)}><ChevronRight /></Button></div></div></Reveal><div className="food-track" ref={track}>{featured.map(dish => <article className="food-card" key={dish.name}><Link to="/menu" aria-label={`Explore ${dish.name}`}><div className="food-image"><img src={dish.image} width="1024" height="1280" alt={`${dish.name}, illustrative food photograph`} loading="lazy" />{dish.popular && <span className="food-badge">POPULAR</span>}</div><div className="food-meta"><span>{dish.category.toUpperCase()}</span><span>✧</span></div><h3>{dish.name}</h3><p>{dish.description}</p><span className="food-link">DISCOVER THE FLAVOUR<ArrowRight /></span></Link></article>)}</div></div></section>;
}
export function MenuSection({ initialCategory = 'Starters' }: { initialCategory?: Category }) {
 const [category, setCategory] = useState<Category>(initialCategory);
 const filtered = dishes.filter(d => d.category === category);
 const tabRefs = useRef<Array<HTMLButtonElement | null>>([]);
 function moveTab(event: React.KeyboardEvent, index: number) {
  if (!['ArrowRight', 'ArrowLeft', 'Home', 'End'].includes(event.key)) return;
  event.preventDefault(); let next = index;
  if (event.key === 'ArrowRight') next = (index + 1) % categories.length;
  if (event.key === 'ArrowLeft') next = (index - 1 + categories.length) % categories.length;
  if (event.key === 'Home') next = 0;
  if (event.key === 'End') next = categories.length - 1;
  const nextCategory = categories[next]; if (nextCategory) { setCategory(nextCategory); tabRefs.current[next]?.focus(); }
 }
 return <section className="section menu-section"><Reveal><div className="menu-heading"><Eyebrow>THE MENU</Eyebrow><h2 className="section-title">A table full of flavours.</h2><p className="section-subtitle">Find your favourite. Discover something new.</p></div></Reveal><div className="menu-tabs" role="tablist" aria-label="Menu categories">{categories.map((item, i) => <Button ref={el => { tabRefs.current[i] = el; }} key={item} id={`tab-${item}`} variant="diningTab" role="tab" aria-selected={category === item} aria-controls="menu-panel" tabIndex={category === item ? 0 : -1} onClick={() => setCategory(item)} onKeyDown={e => moveTab(e, i)}>{item}</Button>)}</div><div className="menu-items" id="menu-panel" role="tabpanel" aria-labelledby={`tab-${category}`} tabIndex={0} key={category}>{filtered.map(dish => <article className="menu-item" key={dish.name}><div><h3>{dish.name}{dish.vegetarian && <span className="diet-dot" aria-label="Vegetarian">◉ VEG</span>}</h3><p>{dish.description}{dish.popular && <span className="text-gold"> · Popular</span>}</p></div><span className="menu-price">Price on request</span></article>)}</div><div className="menu-footer"><Button asChild variant="diningOutline"><a href={restaurant.menu} target="_blank" rel="noreferrer">VIEW FULL MENU<ArrowUpRight /></a></Button><p className="menu-note">Menu highlights. Please confirm current prices and availability with the restaurant.</p></div></section>;
}
export function MandiFeature() {
 return <section className="immersive"><img src={images.mandi} alt="Roasted chicken and aromatic mandi rice on a brass platter, illustrative photograph" width="1920" height="1088" loading="lazy" /><div className="immersive-content mandi-content"><Eyebrow>THE ART OF MANDI</Eyebrow><h2>Slow-Cooked.<br />Fragrant.<br /><em>Unforgettable.</em></h2><p>Discover aromatic rice, perfectly cooked meat and the rich flavours that make every Mandi experience memorable.</p><Button asChild variant="diningOutline"><Link to="/menu" search={{ category: 'Mandi' }}>EXPLORE MANDI<ArrowUpRight /></Link></Button></div></section>;
}
export function GrillSection() {
 return <section className="section grill-section"><Reveal><div className="grill-image reveal-image"><img src={images.grills} alt="Char-grilled kebabs and grilled vegetables, illustrative photograph" width="1024" height="1280" loading="lazy" /></div></Reveal><Reveal className="grill-content"><Eyebrow>FROM THE FLAME</Eyebrow><h2 className="section-title">Smoky. Charred.<br />Full of Character.</h2><p className="section-copy">There’s something irresistible about food from the flame. Discover our kebabs, barbecue favourites and generous platters — a delicious reason to gather around.</p><Link to="/menu" search={{ category: 'Kebabs' }} className="text-link">EXPLORE OUR GRILLS<ArrowUpRight /></Link><svg className="flame-art" viewBox="0 0 70 90" fill="none" stroke="currentColor" strokeWidth="1.2" aria-hidden="true"><path d="M35 4C45 29 17 30 27 47C36 45 40 34 42 29C63 49 69 66 52 79C40 90 17 84 10 68C0 43 22 36 35 4ZM35 56C47 71 47 80 36 82C24 82 26 70 35 56Z" /></svg></Reveal></section>;
}
export function BanquetSection() {
 return <section className="banquet-section"><div className="section"><Reveal><div className="banquet-heading"><Eyebrow>MAKE IT A CELEBRATION</Eyebrow><h2 className="section-title">Some Moments Deserve<br />a Beautiful Setting.</h2><p className="section-copy">From family gatherings to special occasions, create memorable moments around a table filled with flavour.</p></div></Reveal><Reveal><div className="banquet-image"><img src={images.banquet} alt="An illustrative Middle Eastern-inspired dining and event setting; not a photograph of the actual venue" width="1536" height="1024" loading="lazy" /><div className="banquet-caption"><p>Your people. Your occasion.<br /><em>Our warm hospitality.</em></p><ReserveButton outline label="ENQUIRE FOR EVENTS" /></div></div></Reveal><div className="event-types">{['Family gatherings', 'Birthday celebrations', 'Corporate events', 'Private parties', 'Special occasions'].map(event => <span key={event}>{event}</span>)}</div></div></section>;
}
export function Gallery() {
 const [selected, setSelected] = useState<number | null>(null);
 const current = selected === null ? undefined : gallery[selected];
 const change = (direction: number) => setSelected(i => i === null ? 0 : (i + direction + gallery.length) % gallery.length);
 return <section className="section"><Reveal><div className="section-head"><div><Eyebrow>A LITTLE TASTE OF FATTOUSH</Eyebrow><h2 className="section-title">Good Food. Beautiful Moments.</h2></div><Link to="/gallery" className="text-link">THE GALLERY<ArrowUpRight /></Link></div></Reveal><div className="gallery-grid">{gallery.map((image, i) => <Button className="gallery-item" variant="diningIcon" key={image.title} onClick={() => setSelected(i)} aria-label={`View ${image.title}`}><img src={image.src} alt={`${image.title}, illustrative photograph`} width="1024" height="1024" loading="lazy" /><span className="gallery-hover">VIEW ↗</span></Button>)}</div><p className="image-caption">Photography is illustrative; food presentation and the actual venue may vary.</p><Dialog.Root open={selected !== null} onOpenChange={open => { if (!open) setSelected(null); }}><Dialog.Portal><Dialog.Overlay /><Dialog.Content className="lightbox-content" onKeyDown={event => { if (event.key === 'ArrowLeft') change(-1); if (event.key === 'ArrowRight') change(1); }}><Dialog.Close asChild><Button variant="diningIcon" className="lightbox-close" aria-label="Close gallery"><X /></Button></Dialog.Close><Dialog.Title className="lightbox-title">{current?.title}</Dialog.Title><Dialog.Description className="sr-only">Illustrative Fattoush food and dining gallery</Dialog.Description>{current && <img className="lightbox-image" src={current.src} alt={current.title} />}<div className="lightbox-bar"><Button variant="diningIcon" onClick={() => change(-1)} aria-label="Previous image"><ChevronLeft /></Button><span aria-live="polite">{selected === null ? 0 : selected + 1} / {gallery.length}</span><Button variant="diningIcon" onClick={() => change(1)} aria-label="Next image"><ChevronRight /></Button></div></Dialog.Content></Dialog.Portal></Dialog.Root></section>;
}
export function Reviews() {
 return <section className="reviews-band"><div className="section review-layout"><Reveal><Eyebrow>WORDS FROM OUR TABLE</Eyebrow><h2 className="section-title">Loved By<br />Our Guests</h2><span className="stars" aria-label="Five stars">★★★★★</span><div className="review-rating"><strong>4.7</strong><span>/ 5</span></div><p className="rating-note">3,315+ reviews · supplied restaurant listing</p></Reveal><Reveal>{reviews.map(review => <article className="review-card" key={review}><span className="stars" aria-hidden="true">★★★★★</span><blockquote>“{review}”</blockquote><p className="review-source">Guest review · supplied restaurant listing</p></article>)}</Reveal></div></section>;
}
export function ExperienceFeatures() {
 const features = [ ['AUTHENTIC FLAVOURS', 'Middle Eastern-inspired dishes prepared with bold flavours.'], ['FAMILY FRIENDLY', 'A welcoming environment for families and groups.'], ['BANQUET EXPERIENCES', 'A space for celebrations and special gatherings.'], ['ATTENTIVE SERVICE', 'Warm hospitality designed around the guest experience.'] ];
 return <section className="section"><Reveal className="experience-grid">{features.map(([name, copy], i) => <article className="experience-item" key={name}><span className="experience-number">0{i + 1}</span><h3>{name}</h3><p>{copy}</p></article>)}</Reveal></section>;
}
export function ReservationCTA() {
 return <section className="immersive reservation-cta"><img src={images.hero} alt="A Middle Eastern dinner table, illustrative photograph" width="1920" height="1088" loading="lazy" /><div className="immersive-content"><Eyebrow>YOUR TABLE IS WAITING</Eyebrow><h2>Gather around.<br /><em>Make it memorable.</em></h2><p>Share something delicious with your favourite people.</p><ReserveButton outline /></div></section>;
}
export function Location() {
 const [mapOriginAllowed, setMapOriginAllowed] = useState(false);
 useEffect(() => { const host = window.location.hostname; setMapOriginAllowed((host.endsWith('.lovable.app') || host.endsWith('.lovableproject.com')) && !host.includes('-devserver-')); }, []);
 const key = import.meta.env['VITE_LOVABLE_CONNECTOR_GOOGLE_MAPS_BROWSER_KEY'];
 const embed = key && mapOriginAllowed ? `https://www.google.com/maps/embed/v1/place?key=${key}&q=${encodeURIComponent(restaurant.address)}` : undefined;
 return <section className="section"><div className="location-grid"><Reveal className="location-details"><Eyebrow>FIND US</Eyebrow><h2 className="section-title">A Warm Welcome<br />in Chennai.</h2><address>425/1A, Nookampalayam Link Rd,<br />Alamelu Manga Puram,<br />Sholinganallur, Chennai,<br />Tamil Nadu 600119</address><div className="location-detail"><h3>OPENING HOURS</h3><p>Closes approximately 11:30 PM.<br />Please call to confirm today’s opening hours.</p></div><div className="location-actions"><Button asChild variant="diningOutline"><a href={restaurant.directions} target="_blank" rel="noreferrer">GET DIRECTIONS<MapPin /></a></Button><Button asChild variant="diningOutline"><a href="/contact">CALL US<Phone /></a></Button></div></Reveal><div className="location-map">{embed ? <iframe title="Fattoush Restaurant location in Sholinganallur, Chennai" src={embed} loading="lazy" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" /> : <div className="map-unavailable"><MapPin className="mx-auto" /><span>Sholinganallur, Chennai</span><a href={restaurant.directions} target="_blank" rel="noreferrer">Open in Google Maps ↗</a></div>}</div></div><div className="contact-line"><div><Eyebrow>LET’S CONNECT</Eyebrow><h3>Good moments begin here.</h3></div><div className="flex flex-col gap-1"><a href={restaurant.telephone}>{restaurant.phone}</a><a href={restaurant.website} target="_blank" rel="noreferrer">fattoush.in ↗</a></div><ReserveButton /></div></section>;
}
