// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inlgipqypmkkmquhplea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlubGdpcHF5cG1ra21xdWhwbGVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEyNjQ3MjksImV4cCI6MjEwNjg0MDcyOX0.RRSSP8xLkUcZKnCzefn8joTiIAxJj0hGAkRTYdqNqhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});